language: python
python:
- 3.6
services:
- postgresql
addons:
  postgresql: '9.4'
before_install:
- openssl aes-256-cbc -K $encrypted_af95b883e696_key -iv $encrypted_af95b883e696_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
branches:
  only:
  - master
before_script:
- psql -c 'create database test_airbnb_rds;' -U postgres
script:
- cd app
- "./manage.py test"
- cd ..
- git add -A
before_deploy:
- zip -r archive.zip .
deploy:
  provider: elasticbeanstalk
  zip_file: archive.zip
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: ap-northeast-2
  app: Airbnb-Project2
  env: Airbnb-Project-dev2
  bucket_name: fc-airbnb-project
  skip_cleanup: true
  on:
    branch: master
